output {
  rabbitmq {
    # Connection parameters
    host => "localhost"
    port => 8910
    vhost => "/"
    user => "insite"
    password => "abacus"

    # Routing parameters
    exchange => "x.routelogbeat.logs"
    exchange_type => "direct"
    key => "log.data"

    # Reliability and persistence
    durable => true
    persistent => true

    message_properties => {
      "content_type" => "application/json"
    }

    # configuration identification
    id => "rabbitmq_routelogbeat_output"
  }
}